version: '3'

services:

  db:
    container_name: 'Laravel-app-db'
    build: ./docker/db
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 13306:3306

  phpmyadmin:
    container_name: 'Laravel-app-phpmyadmin'
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=Laravel-app-db
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - 18080:80

  redis:
    container_name: 'Laravel-app-redis'
    image: redis:3
    ports:
      - 16379:6379
    command: redis-server --appendonly yes
    volumes:
      - ./docker/redis/data:/data:delegated

  server:
    container_name: 'Laravel-app-server'
    image: nginx
    restart: on-failure
    ports:
      - 180:80
    volumes:
      - ./docker/nginx/conf/site-default.conf:/etc/nginx/conf.d/default.conf
      - ./server:/srv:cached
    depends_on:
      - php-fpm

  php-fpm:
    container_name: 'Laravel-app-php-fpm'
    build: ./docker/php-fpm
    restart: on-failure
    volumes:
      - ./server:/srv:cached

  composer:
    container_name: 'Laravel-app-composer'
    image: composer
    command: 'composer install -o --ignore-platform-reqs'
    volumes:
      - ./server:/srv:delegated
    working_dir: /srv
